// Package audit provides comprehensive audit logging for reaction operations.
// Audit logging is architecturally mandatory - the audit system is always present
// and records every reaction operation.
package audit

import (
	"time"
)

// Operation represents the type of reaction operation being audited.
type Operation string

const (
	// OperationAdd represents adding a new reaction.
	OperationAdd Operation = "ADD"
	// OperationReplace represents replacing an existing reaction.
	OperationReplace Operation = "REPLACE"
	// OperationRemove represents removing a reaction.
	OperationRemove Operation = "REMOVE"
)

// Entry represents a single audit log entry for a reaction operation.
// All fields are required and represent an immutable record of the operation.
type Entry struct {
	// ID is the unique identifier for this audit entry.
	ID string

	// Operation is the type of operation performed (ADD, REPLACE, REMOVE).
	Operation Operation

	// UserID identifies the user who performed the operation.
	UserID string

	// EntityType is the type of entity that was reacted to.
	EntityType string

	// EntityID is the identifier of the entity that was reacted to.
	EntityID string

	// ReactionType is the reaction type after the operation.
	// For REMOVE operations, this will be empty.
	ReactionType string

	// PreviousReaction is the reaction type before the operation.
	// Empty if no previous reaction existed.
	PreviousReaction string

	// Timestamp is when the operation occurred, in UTC with millisecond precision.
	Timestamp time.Time
}

// NewEntry creates a new audit entry with the current UTC timestamp.
// The ID must be generated by the storage implementation.
func NewEntry(operation Operation, userID, entityType, entityID, reactionType, previousReaction string) Entry {
	return Entry{
		Operation:        operation,
		UserID:           userID,
		EntityType:       entityType,
		EntityID:         entityID,
		ReactionType:     reactionType,
		PreviousReaction: previousReaction,
		Timestamp:        time.Now().UTC(),
	}
}
